<?xml version="1.0" encoding="utf-8"?><Database Name="haodian8" Class="HakoneDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=121.199.73.166;Initial Catalog=haodian8;User ID=sa" SettingsObjectName="Hakone.Domain.Properties.Settings" SettingsPropertyName="haodian8ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OAuth2" Member="OAuth2s">
    <Type Name="OAuth2">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="OpenID" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="OAuthServer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ExpireTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HeadUrl" Type="System.String" DbType="VarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="BindAccount" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ProductCategory" Member="ProductCategories">
    <Type Name="ProductCategory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TaoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShopCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Keyword" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Finished" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ShopCategory" Member="ShopCategories">
    <Type Name="ShopCategory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProdcutCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ShopComment" Member="ShopComments">
    <Type Name="ShopComment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShopID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CommentContent" Type="System.String" DbType="NVarChar(1050) NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CommentFlag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BindAccount" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Wangwang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastActiveIP" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BornYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BornMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BornDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActivated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NewPasswordKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NewPasswordKeyRequested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoginTimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Signature" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IsAutoAdded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShopID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TryCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_User" Member="User2" ThisKey="UserID" OtherKey="UserID" Type="User" Cardinality="One" />
      <Association Name="User_User" Member="User1" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserFavProducts" Member="UserFavProducts">
    <Type Name="UserFavProduct">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserFavShops" Member="UserFavShops">
    <Type Name="UserFavShop">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShopID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductIndex" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(320) NOT NULL" CanBeNull="false" />
      <Column Name="DirectTimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RecommendDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastCollectionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsRecommend" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AmountSales" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChecked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CatId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShopId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultSortDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SortNewNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortSalesNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AsyncDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Shops" Member="Shops">
    <Type Name="Shop">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShopOwerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ShopName" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="ShopOwner" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ShopOwerQQ" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="WangWang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MainBiz" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FavNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShopIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RecommendDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastCollectionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsRecommend" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShopViews" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RedirectTimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PromoteURL" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="ShortDesc" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="DescriptionDetail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PromoteAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="PromoteAccount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsChecked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSelected" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHot" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HotDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SelectedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ShopTags" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CatId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FetchDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ShopUrl" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AsyncDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>