#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honshu.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="haodian8")]
	public partial class HonshuDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProductCategory(ProductCategory instance);
    partial void UpdateProductCategory(ProductCategory instance);
    partial void DeleteProductCategory(ProductCategory instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertShopCategory(ShopCategory instance);
    partial void UpdateShopCategory(ShopCategory instance);
    partial void DeleteShopCategory(ShopCategory instance);
    partial void InsertShopComment(ShopComment instance);
    partial void UpdateShopComment(ShopComment instance);
    partial void DeleteShopComment(ShopComment instance);
    partial void InsertShop(Shop instance);
    partial void UpdateShop(Shop instance);
    partial void DeleteShop(Shop instance);
    #endregion
		
		public HonshuDBDataContext() : 
				base(global::Honshu.Data.Properties.Settings.Default.haodian8ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HonshuDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HonshuDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HonshuDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HonshuDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProductCategory> ProductCategories
		{
			get
			{
				return this.GetTable<ProductCategory>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<ShopCategory> ShopCategories
		{
			get
			{
				return this.GetTable<ShopCategory>();
			}
		}
		
		public System.Data.Linq.Table<ShopComment> ShopComments
		{
			get
			{
				return this.GetTable<ShopComment>();
			}
		}
		
		public System.Data.Linq.Table<Shop> Shops
		{
			get
			{
				return this.GetTable<Shop>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductCategory")]
	public partial class ProductCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CategoryName;
		
		private int _TaoID;
		
		private System.Nullable<int> _ShopCategoryId;
		
		private string _Keyword;
		
		private bool _Finished;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    partial void OnTaoIDChanging(int value);
    partial void OnTaoIDChanged();
    partial void OnShopCategoryIdChanging(System.Nullable<int> value);
    partial void OnShopCategoryIdChanged();
    partial void OnKeywordChanging(string value);
    partial void OnKeywordChanged();
    partial void OnFinishedChanging(bool value);
    partial void OnFinishedChanged();
    #endregion
		
		public ProductCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaoID", DbType="Int NOT NULL")]
		public int TaoID
		{
			get
			{
				return this._TaoID;
			}
			set
			{
				if ((this._TaoID != value))
				{
					this.OnTaoIDChanging(value);
					this.SendPropertyChanging();
					this._TaoID = value;
					this.SendPropertyChanged("TaoID");
					this.OnTaoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopCategoryId", DbType="Int")]
		public System.Nullable<int> ShopCategoryId
		{
			get
			{
				return this._ShopCategoryId;
			}
			set
			{
				if ((this._ShopCategoryId != value))
				{
					this.OnShopCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._ShopCategoryId = value;
					this.SendPropertyChanged("ShopCategoryId");
					this.OnShopCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this.OnKeywordChanging(value);
					this.SendPropertyChanging();
					this._Keyword = value;
					this.SendPropertyChanged("Keyword");
					this.OnKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finished", DbType="Bit NOT NULL")]
		public bool Finished
		{
			get
			{
				return this._Finished;
			}
			set
			{
				if ((this._Finished != value))
				{
					this.OnFinishedChanging(value);
					this.SendPropertyChanging();
					this._Finished = value;
					this.SendPropertyChanged("Finished");
					this.OnFinishedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private long _ProductIndex;
		
		private string _ProductName;
		
		private decimal _Price;
		
		private string _Photo;
		
		private int _DirectTimes;
		
		private System.DateTime _EntryDate;
		
		private System.DateTime _UpdateDate;
		
		private System.DateTime _RecommendDate;
		
		private System.DateTime _LastCollectionDate;
		
		private bool _IsRecommend;
		
		private int _AmountSales;
		
		private bool _IsDeleted;
		
		private bool _IsChecked;
		
		private int _CatId;
		
		private int _ShopId;
		
		private System.DateTime _DefaultSortDate;
		
		private int _SortNewNumber;
		
		private int _SortSalesNumber;
		
		private System.DateTime _AsyncDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnProductIndexChanging(long value);
    partial void OnProductIndexChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnDirectTimesChanging(int value);
    partial void OnDirectTimesChanged();
    partial void OnEntryDateChanging(System.DateTime value);
    partial void OnEntryDateChanged();
    partial void OnUpdateDateChanging(System.DateTime value);
    partial void OnUpdateDateChanged();
    partial void OnRecommendDateChanging(System.DateTime value);
    partial void OnRecommendDateChanged();
    partial void OnLastCollectionDateChanging(System.DateTime value);
    partial void OnLastCollectionDateChanged();
    partial void OnIsRecommendChanging(bool value);
    partial void OnIsRecommendChanged();
    partial void OnAmountSalesChanging(int value);
    partial void OnAmountSalesChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnIsCheckedChanging(bool value);
    partial void OnIsCheckedChanged();
    partial void OnCatIdChanging(int value);
    partial void OnCatIdChanged();
    partial void OnShopIdChanging(int value);
    partial void OnShopIdChanged();
    partial void OnDefaultSortDateChanging(System.DateTime value);
    partial void OnDefaultSortDateChanged();
    partial void OnSortNewNumberChanging(int value);
    partial void OnSortNewNumberChanged();
    partial void OnSortSalesNumberChanging(int value);
    partial void OnSortSalesNumberChanged();
    partial void OnAsyncDateChanging(System.DateTime value);
    partial void OnAsyncDateChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductIndex", DbType="BigInt NOT NULL")]
		public long ProductIndex
		{
			get
			{
				return this._ProductIndex;
			}
			set
			{
				if ((this._ProductIndex != value))
				{
					this.OnProductIndexChanging(value);
					this.SendPropertyChanging();
					this._ProductIndex = value;
					this.SendPropertyChanged("ProductIndex");
					this.OnProductIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(8,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="VarChar(320) NOT NULL", CanBeNull=false)]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectTimes", DbType="Int NOT NULL")]
		public int DirectTimes
		{
			get
			{
				return this._DirectTimes;
			}
			set
			{
				if ((this._DirectTimes != value))
				{
					this.OnDirectTimesChanging(value);
					this.SendPropertyChanging();
					this._DirectTimes = value;
					this.SendPropertyChanged("DirectTimes");
					this.OnDirectTimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime NOT NULL")]
		public System.DateTime EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this.OnEntryDateChanging(value);
					this.SendPropertyChanging();
					this._EntryDate = value;
					this.SendPropertyChanged("EntryDate");
					this.OnEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecommendDate", DbType="DateTime NOT NULL")]
		public System.DateTime RecommendDate
		{
			get
			{
				return this._RecommendDate;
			}
			set
			{
				if ((this._RecommendDate != value))
				{
					this.OnRecommendDateChanging(value);
					this.SendPropertyChanging();
					this._RecommendDate = value;
					this.SendPropertyChanged("RecommendDate");
					this.OnRecommendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCollectionDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastCollectionDate
		{
			get
			{
				return this._LastCollectionDate;
			}
			set
			{
				if ((this._LastCollectionDate != value))
				{
					this.OnLastCollectionDateChanging(value);
					this.SendPropertyChanging();
					this._LastCollectionDate = value;
					this.SendPropertyChanged("LastCollectionDate");
					this.OnLastCollectionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRecommend", DbType="Bit NOT NULL")]
		public bool IsRecommend
		{
			get
			{
				return this._IsRecommend;
			}
			set
			{
				if ((this._IsRecommend != value))
				{
					this.OnIsRecommendChanging(value);
					this.SendPropertyChanging();
					this._IsRecommend = value;
					this.SendPropertyChanged("IsRecommend");
					this.OnIsRecommendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountSales", DbType="Int NOT NULL")]
		public int AmountSales
		{
			get
			{
				return this._AmountSales;
			}
			set
			{
				if ((this._AmountSales != value))
				{
					this.OnAmountSalesChanging(value);
					this.SendPropertyChanging();
					this._AmountSales = value;
					this.SendPropertyChanged("AmountSales");
					this.OnAmountSalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChecked", DbType="Bit NOT NULL")]
		public bool IsChecked
		{
			get
			{
				return this._IsChecked;
			}
			set
			{
				if ((this._IsChecked != value))
				{
					this.OnIsCheckedChanging(value);
					this.SendPropertyChanging();
					this._IsChecked = value;
					this.SendPropertyChanged("IsChecked");
					this.OnIsCheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatId", DbType="Int NOT NULL")]
		public int CatId
		{
			get
			{
				return this._CatId;
			}
			set
			{
				if ((this._CatId != value))
				{
					this.OnCatIdChanging(value);
					this.SendPropertyChanging();
					this._CatId = value;
					this.SendPropertyChanged("CatId");
					this.OnCatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopId", DbType="Int NOT NULL")]
		public int ShopId
		{
			get
			{
				return this._ShopId;
			}
			set
			{
				if ((this._ShopId != value))
				{
					this.OnShopIdChanging(value);
					this.SendPropertyChanging();
					this._ShopId = value;
					this.SendPropertyChanged("ShopId");
					this.OnShopIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultSortDate", DbType="DateTime NOT NULL")]
		public System.DateTime DefaultSortDate
		{
			get
			{
				return this._DefaultSortDate;
			}
			set
			{
				if ((this._DefaultSortDate != value))
				{
					this.OnDefaultSortDateChanging(value);
					this.SendPropertyChanging();
					this._DefaultSortDate = value;
					this.SendPropertyChanged("DefaultSortDate");
					this.OnDefaultSortDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortNewNumber", DbType="Int NOT NULL")]
		public int SortNewNumber
		{
			get
			{
				return this._SortNewNumber;
			}
			set
			{
				if ((this._SortNewNumber != value))
				{
					this.OnSortNewNumberChanging(value);
					this.SendPropertyChanging();
					this._SortNewNumber = value;
					this.SendPropertyChanged("SortNewNumber");
					this.OnSortNewNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortSalesNumber", DbType="Int NOT NULL")]
		public int SortSalesNumber
		{
			get
			{
				return this._SortSalesNumber;
			}
			set
			{
				if ((this._SortSalesNumber != value))
				{
					this.OnSortSalesNumberChanging(value);
					this.SendPropertyChanging();
					this._SortSalesNumber = value;
					this.SendPropertyChanged("SortSalesNumber");
					this.OnSortSalesNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsyncDate", DbType="DateTime NOT NULL")]
		public System.DateTime AsyncDate
		{
			get
			{
				return this._AsyncDate;
			}
			set
			{
				if ((this._AsyncDate != value))
				{
					this.OnAsyncDateChanging(value);
					this.SendPropertyChanging();
					this._AsyncDate = value;
					this.SendPropertyChanged("AsyncDate");
					this.OnAsyncDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShopCategory")]
	public partial class ShopCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CategoryName;
		
		private int _ProdcutCategoryId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    partial void OnProdcutCategoryIdChanging(int value);
    partial void OnProdcutCategoryIdChanged();
    #endregion
		
		public ShopCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdcutCategoryId", DbType="Int NOT NULL")]
		public int ProdcutCategoryId
		{
			get
			{
				return this._ProdcutCategoryId;
			}
			set
			{
				if ((this._ProdcutCategoryId != value))
				{
					this.OnProdcutCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._ProdcutCategoryId = value;
					this.SendPropertyChanged("ProdcutCategoryId");
					this.OnProdcutCategoryIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShopComment")]
	public partial class ShopComment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private long _ShopID;
		
		private string _CommentContent;
		
		private System.DateTime _EntryDate;
		
		private int _CommentFlag;
		
		private int _UserId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnShopIDChanging(long value);
    partial void OnShopIDChanged();
    partial void OnCommentContentChanging(string value);
    partial void OnCommentContentChanged();
    partial void OnEntryDateChanging(System.DateTime value);
    partial void OnEntryDateChanged();
    partial void OnCommentFlagChanging(int value);
    partial void OnCommentFlagChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    #endregion
		
		public ShopComment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopID", DbType="BigInt NOT NULL")]
		public long ShopID
		{
			get
			{
				return this._ShopID;
			}
			set
			{
				if ((this._ShopID != value))
				{
					this.OnShopIDChanging(value);
					this.SendPropertyChanging();
					this._ShopID = value;
					this.SendPropertyChanged("ShopID");
					this.OnShopIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentContent", DbType="NVarChar(1050) NOT NULL", CanBeNull=false)]
		public string CommentContent
		{
			get
			{
				return this._CommentContent;
			}
			set
			{
				if ((this._CommentContent != value))
				{
					this.OnCommentContentChanging(value);
					this.SendPropertyChanging();
					this._CommentContent = value;
					this.SendPropertyChanged("CommentContent");
					this.OnCommentContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime NOT NULL")]
		public System.DateTime EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this.OnEntryDateChanging(value);
					this.SendPropertyChanging();
					this._EntryDate = value;
					this.SendPropertyChanged("EntryDate");
					this.OnEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentFlag", DbType="Int NOT NULL")]
		public int CommentFlag
		{
			get
			{
				return this._CommentFlag;
			}
			set
			{
				if ((this._CommentFlag != value))
				{
					this.OnCommentFlagChanging(value);
					this.SendPropertyChanging();
					this._CommentFlag = value;
					this.SendPropertyChanged("CommentFlag");
					this.OnCommentFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shops")]
	public partial class Shop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private long _ShopOwerID;
		
		private string _ShopName;
		
		private string _ShopOwner;
		
		private string _ShopOwerQQ;
		
		private string _Photo;
		
		private string _WangWang;
		
		private string _MainBiz;
		
		private int _FavNum;
		
		private string _City;
		
		private int _ShopIndex;
		
		private System.DateTime _EntryDate;
		
		private System.DateTime _LastModifyDate;
		
		private System.DateTime _RecommendDate;
		
		private System.DateTime _LastCollectionDate;
		
		private bool _IsRecommend;
		
		private int _ShopViews;
		
		private int _RedirectTimes;
		
		private string _PromoteURL;
		
		private string _ShortDesc;
		
		private string _DescriptionDetail;
		
		private bool _IsDeleted;
		
		private decimal _PromoteAmount;
		
		private int _PromoteAccount;
		
		private bool _IsChecked;
		
		private bool _IsSelected;
		
		private bool _IsHot;
		
		private System.DateTime _HotDate;
		
		private System.DateTime _SelectedDate;
		
		private string _ShopTags;
		
		private int _CatId;
		
		private System.DateTime _FetchDate;
		
		private string _ShopUrl;
		
		private System.DateTime _AsyncDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnShopOwerIDChanging(long value);
    partial void OnShopOwerIDChanged();
    partial void OnShopNameChanging(string value);
    partial void OnShopNameChanged();
    partial void OnShopOwnerChanging(string value);
    partial void OnShopOwnerChanged();
    partial void OnShopOwerQQChanging(string value);
    partial void OnShopOwerQQChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnWangWangChanging(string value);
    partial void OnWangWangChanged();
    partial void OnMainBizChanging(string value);
    partial void OnMainBizChanged();
    partial void OnFavNumChanging(int value);
    partial void OnFavNumChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnShopIndexChanging(int value);
    partial void OnShopIndexChanged();
    partial void OnEntryDateChanging(System.DateTime value);
    partial void OnEntryDateChanged();
    partial void OnLastModifyDateChanging(System.DateTime value);
    partial void OnLastModifyDateChanged();
    partial void OnRecommendDateChanging(System.DateTime value);
    partial void OnRecommendDateChanged();
    partial void OnLastCollectionDateChanging(System.DateTime value);
    partial void OnLastCollectionDateChanged();
    partial void OnIsRecommendChanging(bool value);
    partial void OnIsRecommendChanged();
    partial void OnShopViewsChanging(int value);
    partial void OnShopViewsChanged();
    partial void OnRedirectTimesChanging(int value);
    partial void OnRedirectTimesChanged();
    partial void OnPromoteURLChanging(string value);
    partial void OnPromoteURLChanged();
    partial void OnShortDescChanging(string value);
    partial void OnShortDescChanged();
    partial void OnDescriptionDetailChanging(string value);
    partial void OnDescriptionDetailChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnPromoteAmountChanging(decimal value);
    partial void OnPromoteAmountChanged();
    partial void OnPromoteAccountChanging(int value);
    partial void OnPromoteAccountChanged();
    partial void OnIsCheckedChanging(bool value);
    partial void OnIsCheckedChanged();
    partial void OnIsSelectedChanging(bool value);
    partial void OnIsSelectedChanged();
    partial void OnIsHotChanging(bool value);
    partial void OnIsHotChanged();
    partial void OnHotDateChanging(System.DateTime value);
    partial void OnHotDateChanged();
    partial void OnSelectedDateChanging(System.DateTime value);
    partial void OnSelectedDateChanged();
    partial void OnShopTagsChanging(string value);
    partial void OnShopTagsChanged();
    partial void OnCatIdChanging(int value);
    partial void OnCatIdChanged();
    partial void OnFetchDateChanging(System.DateTime value);
    partial void OnFetchDateChanged();
    partial void OnShopUrlChanging(string value);
    partial void OnShopUrlChanged();
    partial void OnAsyncDateChanging(System.DateTime value);
    partial void OnAsyncDateChanged();
    #endregion
		
		public Shop()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopOwerID", DbType="BigInt NOT NULL")]
		public long ShopOwerID
		{
			get
			{
				return this._ShopOwerID;
			}
			set
			{
				if ((this._ShopOwerID != value))
				{
					this.OnShopOwerIDChanging(value);
					this.SendPropertyChanging();
					this._ShopOwerID = value;
					this.SendPropertyChanged("ShopOwerID");
					this.OnShopOwerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopName", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string ShopName
		{
			get
			{
				return this._ShopName;
			}
			set
			{
				if ((this._ShopName != value))
				{
					this.OnShopNameChanging(value);
					this.SendPropertyChanging();
					this._ShopName = value;
					this.SendPropertyChanged("ShopName");
					this.OnShopNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopOwner", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ShopOwner
		{
			get
			{
				return this._ShopOwner;
			}
			set
			{
				if ((this._ShopOwner != value))
				{
					this.OnShopOwnerChanging(value);
					this.SendPropertyChanging();
					this._ShopOwner = value;
					this.SendPropertyChanged("ShopOwner");
					this.OnShopOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopOwerQQ", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ShopOwerQQ
		{
			get
			{
				return this._ShopOwerQQ;
			}
			set
			{
				if ((this._ShopOwerQQ != value))
				{
					this.OnShopOwerQQChanging(value);
					this.SendPropertyChanging();
					this._ShopOwerQQ = value;
					this.SendPropertyChanged("ShopOwerQQ");
					this.OnShopOwerQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="VarChar(450) NOT NULL", CanBeNull=false)]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WangWang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string WangWang
		{
			get
			{
				return this._WangWang;
			}
			set
			{
				if ((this._WangWang != value))
				{
					this.OnWangWangChanging(value);
					this.SendPropertyChanging();
					this._WangWang = value;
					this.SendPropertyChanged("WangWang");
					this.OnWangWangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainBiz", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string MainBiz
		{
			get
			{
				return this._MainBiz;
			}
			set
			{
				if ((this._MainBiz != value))
				{
					this.OnMainBizChanging(value);
					this.SendPropertyChanging();
					this._MainBiz = value;
					this.SendPropertyChanged("MainBiz");
					this.OnMainBizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FavNum", DbType="Int NOT NULL")]
		public int FavNum
		{
			get
			{
				return this._FavNum;
			}
			set
			{
				if ((this._FavNum != value))
				{
					this.OnFavNumChanging(value);
					this.SendPropertyChanging();
					this._FavNum = value;
					this.SendPropertyChanged("FavNum");
					this.OnFavNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopIndex", DbType="Int NOT NULL")]
		public int ShopIndex
		{
			get
			{
				return this._ShopIndex;
			}
			set
			{
				if ((this._ShopIndex != value))
				{
					this.OnShopIndexChanging(value);
					this.SendPropertyChanging();
					this._ShopIndex = value;
					this.SendPropertyChanged("ShopIndex");
					this.OnShopIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime NOT NULL")]
		public System.DateTime EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this.OnEntryDateChanging(value);
					this.SendPropertyChanging();
					this._EntryDate = value;
					this.SendPropertyChanged("EntryDate");
					this.OnEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifyDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifyDate
		{
			get
			{
				return this._LastModifyDate;
			}
			set
			{
				if ((this._LastModifyDate != value))
				{
					this.OnLastModifyDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifyDate = value;
					this.SendPropertyChanged("LastModifyDate");
					this.OnLastModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecommendDate", DbType="DateTime NOT NULL")]
		public System.DateTime RecommendDate
		{
			get
			{
				return this._RecommendDate;
			}
			set
			{
				if ((this._RecommendDate != value))
				{
					this.OnRecommendDateChanging(value);
					this.SendPropertyChanging();
					this._RecommendDate = value;
					this.SendPropertyChanged("RecommendDate");
					this.OnRecommendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCollectionDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastCollectionDate
		{
			get
			{
				return this._LastCollectionDate;
			}
			set
			{
				if ((this._LastCollectionDate != value))
				{
					this.OnLastCollectionDateChanging(value);
					this.SendPropertyChanging();
					this._LastCollectionDate = value;
					this.SendPropertyChanged("LastCollectionDate");
					this.OnLastCollectionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRecommend", DbType="Bit NOT NULL")]
		public bool IsRecommend
		{
			get
			{
				return this._IsRecommend;
			}
			set
			{
				if ((this._IsRecommend != value))
				{
					this.OnIsRecommendChanging(value);
					this.SendPropertyChanging();
					this._IsRecommend = value;
					this.SendPropertyChanged("IsRecommend");
					this.OnIsRecommendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopViews", DbType="Int NOT NULL")]
		public int ShopViews
		{
			get
			{
				return this._ShopViews;
			}
			set
			{
				if ((this._ShopViews != value))
				{
					this.OnShopViewsChanging(value);
					this.SendPropertyChanging();
					this._ShopViews = value;
					this.SendPropertyChanged("ShopViews");
					this.OnShopViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RedirectTimes", DbType="Int NOT NULL")]
		public int RedirectTimes
		{
			get
			{
				return this._RedirectTimes;
			}
			set
			{
				if ((this._RedirectTimes != value))
				{
					this.OnRedirectTimesChanging(value);
					this.SendPropertyChanging();
					this._RedirectTimes = value;
					this.SendPropertyChanged("RedirectTimes");
					this.OnRedirectTimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromoteURL", DbType="NVarChar(350) NOT NULL", CanBeNull=false)]
		public string PromoteURL
		{
			get
			{
				return this._PromoteURL;
			}
			set
			{
				if ((this._PromoteURL != value))
				{
					this.OnPromoteURLChanging(value);
					this.SendPropertyChanging();
					this._PromoteURL = value;
					this.SendPropertyChanged("PromoteURL");
					this.OnPromoteURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDesc", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string ShortDesc
		{
			get
			{
				return this._ShortDesc;
			}
			set
			{
				if ((this._ShortDesc != value))
				{
					this.OnShortDescChanging(value);
					this.SendPropertyChanging();
					this._ShortDesc = value;
					this.SendPropertyChanged("ShortDesc");
					this.OnShortDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionDetail", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DescriptionDetail
		{
			get
			{
				return this._DescriptionDetail;
			}
			set
			{
				if ((this._DescriptionDetail != value))
				{
					this.OnDescriptionDetailChanging(value);
					this.SendPropertyChanging();
					this._DescriptionDetail = value;
					this.SendPropertyChanged("DescriptionDetail");
					this.OnDescriptionDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromoteAmount", DbType="Decimal(18,2) NOT NULL")]
		public decimal PromoteAmount
		{
			get
			{
				return this._PromoteAmount;
			}
			set
			{
				if ((this._PromoteAmount != value))
				{
					this.OnPromoteAmountChanging(value);
					this.SendPropertyChanging();
					this._PromoteAmount = value;
					this.SendPropertyChanged("PromoteAmount");
					this.OnPromoteAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromoteAccount", DbType="Int NOT NULL")]
		public int PromoteAccount
		{
			get
			{
				return this._PromoteAccount;
			}
			set
			{
				if ((this._PromoteAccount != value))
				{
					this.OnPromoteAccountChanging(value);
					this.SendPropertyChanging();
					this._PromoteAccount = value;
					this.SendPropertyChanged("PromoteAccount");
					this.OnPromoteAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChecked", DbType="Bit NOT NULL")]
		public bool IsChecked
		{
			get
			{
				return this._IsChecked;
			}
			set
			{
				if ((this._IsChecked != value))
				{
					this.OnIsCheckedChanging(value);
					this.SendPropertyChanging();
					this._IsChecked = value;
					this.SendPropertyChanged("IsChecked");
					this.OnIsCheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSelected", DbType="Bit NOT NULL")]
		public bool IsSelected
		{
			get
			{
				return this._IsSelected;
			}
			set
			{
				if ((this._IsSelected != value))
				{
					this.OnIsSelectedChanging(value);
					this.SendPropertyChanging();
					this._IsSelected = value;
					this.SendPropertyChanged("IsSelected");
					this.OnIsSelectedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHot", DbType="Bit NOT NULL")]
		public bool IsHot
		{
			get
			{
				return this._IsHot;
			}
			set
			{
				if ((this._IsHot != value))
				{
					this.OnIsHotChanging(value);
					this.SendPropertyChanging();
					this._IsHot = value;
					this.SendPropertyChanged("IsHot");
					this.OnIsHotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotDate", DbType="DateTime NOT NULL")]
		public System.DateTime HotDate
		{
			get
			{
				return this._HotDate;
			}
			set
			{
				if ((this._HotDate != value))
				{
					this.OnHotDateChanging(value);
					this.SendPropertyChanging();
					this._HotDate = value;
					this.SendPropertyChanged("HotDate");
					this.OnHotDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectedDate", DbType="DateTime NOT NULL")]
		public System.DateTime SelectedDate
		{
			get
			{
				return this._SelectedDate;
			}
			set
			{
				if ((this._SelectedDate != value))
				{
					this.OnSelectedDateChanging(value);
					this.SendPropertyChanging();
					this._SelectedDate = value;
					this.SendPropertyChanged("SelectedDate");
					this.OnSelectedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopTags", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ShopTags
		{
			get
			{
				return this._ShopTags;
			}
			set
			{
				if ((this._ShopTags != value))
				{
					this.OnShopTagsChanging(value);
					this.SendPropertyChanging();
					this._ShopTags = value;
					this.SendPropertyChanged("ShopTags");
					this.OnShopTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatId", DbType="Int NOT NULL")]
		public int CatId
		{
			get
			{
				return this._CatId;
			}
			set
			{
				if ((this._CatId != value))
				{
					this.OnCatIdChanging(value);
					this.SendPropertyChanging();
					this._CatId = value;
					this.SendPropertyChanged("CatId");
					this.OnCatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FetchDate", DbType="DateTime NOT NULL")]
		public System.DateTime FetchDate
		{
			get
			{
				return this._FetchDate;
			}
			set
			{
				if ((this._FetchDate != value))
				{
					this.OnFetchDateChanging(value);
					this.SendPropertyChanging();
					this._FetchDate = value;
					this.SendPropertyChanged("FetchDate");
					this.OnFetchDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopUrl", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ShopUrl
		{
			get
			{
				return this._ShopUrl;
			}
			set
			{
				if ((this._ShopUrl != value))
				{
					this.OnShopUrlChanging(value);
					this.SendPropertyChanging();
					this._ShopUrl = value;
					this.SendPropertyChanged("ShopUrl");
					this.OnShopUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsyncDate", DbType="DateTime NOT NULL")]
		public System.DateTime AsyncDate
		{
			get
			{
				return this._AsyncDate;
			}
			set
			{
				if ((this._AsyncDate != value))
				{
					this.OnAsyncDateChanging(value);
					this.SendPropertyChanging();
					this._AsyncDate = value;
					this.SendPropertyChanged("AsyncDate");
					this.OnAsyncDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
